import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Philipe Morais - Desenvolvedor Front-End & Designer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body>{children}</body>
    </html>
  )
}
