import Head from 'next/head'

import { Main } from '../components/Main'
import { About } from '../components/About'
import { Skills } from '../components/Skills'
import { Projects } from '../components/Projects'
import { Contact } from '../components/Contact'
import { Experiences } from '../components/Experiences'

const Home = () => {
  return (
    <div className='scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#4A9B7F]/80'>
      <Head>
        <title>Philipe Morais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/LogoCompleta.png" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Experiences />
      <Projects />
      <Contact />
    </div>
  )
}

export default Home;